### PR TITLE
Fixed broken troop count when support is in the village + minor fix

### PR DESCRIPTION
**Pull request by acroticguy**
Changed units_in_village(), so that the data taken is only about the units "From this village" as the name suggests. 

Data fetched comes from the rally point page, so instead of initializing a new variable I simply moved up "get_all", and used "result_all" to get the data needed.

Since many times the scavenging would be done while the bot was running farms, I also added another troop check once scavenging begins.

### CODE REVIEW

**Comment by stefan2200** [comment]
Hey man, great work but I noticed whenever I try this it does not detect any troops. I'm guessing it is because of the string `From this village` which is translated in other versions of the game. I think the best (universal) implementation would be to create a negative search which filters out all of the rows that have the support logo.

**Comment by acroticguy** [comment]
> Hey man, great work but I noticed whenever I try this it does not detect any troops. I'm guessing it is because of the string `From this village` which is translated in other versions of the game. I think the best (universal) implementation would be to create a negative search which filters out all of the rows that have the support logo.

Damn! What a blunder on my part hahahah. I did some digging and I figured a solution that might not need that big of a change, but is still fairly silly (your negative search makes so much more sense). The idea is that since the "From this village" row is always going to be the 2nd row of the table, I could change the regex to something like this: 

<table id="units_home".*?</tr>(.*?)</tr>

Meaning we do start from "units_home" which is a universal ID, but only match the 2nd row of items. On my side tests it seems to be working fine, I'll try it within TWB to see the results.

**Comment by acroticguy** [comment]
I can confirm, with the new regex the bot appears to work just fine still. Would you mind trying it in the server you are using?

**Comment by stefan2200** [comment]
Confirmed, working on three different servers 👍

**Comment by acroticguy** [comment]
Pushed the new commit!

**Pull request merged**
