### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by Zaninbm**
Well the guy have updated the code recently, thank u for your effort!

### CODE REVIEW

**Comment by stefan2200** [comment]
Wow, those are a lot of changes!

@davidakachaos thanks for the effort man!
Since I am not playing TW (anymore?) I can make you a maintainer if you like? or you can just work on your own fork :)

**Comment by davidakachaos** [comment]
Oh, I'm just pushing changes to my own fork as I find things I want to change. As you can see from the terrible commit messages it's like an ad hoc kind of style :smile: But if anyone has any requests for changes, or ideas, I'm open to suggestions :wink:

**Comment by stefan2200** [comment]
Haha I noticed, that is why I tagged the guy :)

**Comment by stefan2200** [comment]
Still, all additions are welcome and they give me at least some working (and more stylish) code once I start "playing" TW again :D

**Comment by stefan2200** [comment]
Awesome, I have some dev version laying around that uses a global resource manager to do that. Worked pretty well but it also requires some sort of prioritization system to keep everything in sync. Btw. I noticed two test cases failed on the GB servers. Not really an issue tbh but its happens a lot when matching on language specific words like `Aankomend:` in the resources file. All TW sites are the same except the text labels. If I find the time I can perhaps take a look if the matching can be more generic so it works on all versions.
Anyway, great work man and if you need any tips feel free to hmu on Discord :)

**Pull request merged**
